### ISSUE TITLE
bug: Google Collab Inference with homebrewltd / Ichigo-llama3.1-s-instruct-v0.4

### ISSUE THREAD

**Issue by PS-AI** [homebrewltd/ichigo#109]

**Comment by PS-AI** [comment]
Hi, @bachvudinh , thank you for your response. I am using "whisper-vq-stoks-medium-en+pl-fixed.model" from the repo "jan-hq/WhisperVQ".  Could you let me know if I have to use something else.

**Comment by bachvudinh** [comment]
@PS-AI please check the lastest google collab notebook i just updated it yesterday. The correct checkpoint should be  whisper-vq-stoks-v3-7lang-fixed.model.
