### ISSUE TITLE
bug: fix </s> issue

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/ichigo#31]
For some reason the model still outputting </s> in some cases even though they don't have this in the training set, need to narrow the root cause

**Comment by 0xSage** [comment]
@tikikun I'm very curious what was the cause of this issue? And were were able to resolve it?

**Comment by tikikun** [comment]
We have not successfully figured out why, we will observe if in the next training run the issue persists, because there is no issue in the code as well as the data, very strange indeed.

**Comment by 0xSage** [comment]
I'm a bit confused by the nature of the issue, bc the original description is quite concise.

Can I clarify: 

1. We're trying to figure out where the </s> stop token comes from?
2. Are we sure it wasn't in the open data sets we used? Or are you saying it could come from the base model?
3. What kind of issue is this causing? Is it that the models are prematurely stopping generation?

**Comment by tikikun** [comment]
fixed
