### ISSUE TITLE
ci: Set up baseline evals using cascaded system

### ISSUE THREAD

**Issue by 0xSage** [homebrewltd/ichigo#38]
## Problem
Systematically evaluate the performance of our multimodal model by comparing it to a baseline benchmark. 
Baseline is a cascaded system of Whisperspeech TTS + LLaMA3.1.

## Suggestions
- LM performance metrics, e.g. MMLU
- Latency metrics

**Comment by tikikun** [comment]
maybe bach have a look? otherwise for latency we have the result here #40
