### ISSUE TITLE
data: Improve hard to pronounce prompts

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/ichigo#54]
## Problem
We can easily improve (synthetic) speech data quality by removing or regenerating hard to pronounce words.

## Examples
Ascii characters:
💡 (speech-to-text models may struggle to recognize the emoji as a word)
⇩ (down arrow symbol may be difficult to pronounce)

Long code chunks:
#include <iostream> using namespace std; (may be hard to pronounce for non-technical speakers)
const char* hello = "Hello, world!"; (technical jargon may be challenging to pronounce)

Other examples:
π (Greek letter may be hard to pronounce for non-mathematical speakers)
① (number symbol may be difficult to read aloud)

## Tool Resources
Using distilabel pipeline.

## Questions
1. How do we identify these types of prompts in the first place?
2. When do we filter out the questions vs.
3. When do we phrase these questions in a more native spoken format

**Comment by 0xSage** [comment]
@homebrewltd/research does this need to be in the next sprint, timing wise? It seems we went ahead with phase 2 already.

**Comment by tikikun** [comment]
This yield un-necessary when we have intelligent models, hard to say it, but when the model instruction following is good enough, you can simply just prompt it to be so. Since the pre-training dataset of most foundational is large enough to contain these types of information

Ichigo is also working very well under this.
