### ISSUE TITLE
experiment: try llama3-s v0.3 on Q8 and Q4

### ISSUE THREAD

**Issue by 0xSage** [homebrewltd/ichigo#63]
## Problem
- Can users run it on iphone?
- Can users run it on PC?
- Will quantized versions be super bad?
- TBA!

## Reference
Informs #62

**Comment by tikikun** [comment]
Here is the benchmark for llama3-s v0.3 (ichigo) with different quantizations

| Data Type | Correct Answers | Confidence |
| --- | --- | --- |
| bf16 | 63.78% | 55.43% |
| int8 | 63.67% | 55.35% |
| int4 | 61.43% | 52.86% |

VRAM usage mostly will match llama3.1
