### ISSUE TITLE
epic: Jade as our Model name?

### ISSUE THREAD

**Issue by dan-homebrew** [homebrewltd/ichigo#64]
## Goal 

- Follow-up of https://github.com/homebrewltd/internal/issues/8
- We should rename `llama-s` to Jade branding
- Jade will carry the name of foundational model, e.g. `jade1-llama3.1-7b`

## Jade's Positioning & Direction

- Jade is built to enable Jan to push the boundaries of what's possible with on-device AI
- Jade can be roughly understood as an "open source Siri"
- Jade is multi-modal, as we want it to hear, see, think and do (i.e. function calling)
- Jade is multi-lingual, as our userbase (and team) are from different countries and culture
- Jade is optimized for Jan use-cases (potentially desktop and phone use-cases in the future)
- Jade will incorporate all new experiments (e.g. CoT, etc) 

We will start off by being based on llama3.1, but may switch to different foundation models in the future. This is similar to one of our inspirations, [MiniCPM-V](https://github.com/OpenBMB/MiniCPM-V). 

## Tasklist

- Repo to be renamed? (might lose SEO)
- Edit README

**Comment by tikikun** [comment]
Hi @dan-homebrew , I wanted to share my thoughts on the naming convention for Jade. While I understand the intention behind using 'Jade' as a voice model, I'm concerned that it might limit the scope of the project in the future.

In my opinion, naming it 'Jade-voice' would be more descriptive and future-proof, as it explicitly indicates that it's a voice model. This could also make it easier to differentiate it from other models that might be developed later, such as 'Mixtral', 'Mistral', or 'Pixtral'.

I think consolidating the naming convention now could help avoid confusion down the line when we have multiple models. Would it be possible to consider this suggestion and discuss it further?

**Comment by julien-blanchon** [comment]
(Random guys here), I really like the name Jade. This might also give you an easy logo idea, using the a designed jade rock ... Plus it's also a female name and this might give some personality to the project

**Comment by tikikun** [comment]
It is already decided that our fate is Ichigo, thanks!
