### ISSUE TITLE
data: Integrate existing open source Voice datasets

### ISSUE THREAD

**Issue by bachvudinh** [homebrewltd/ichigo#65]
Found a very interesting and high quality data that used to train GPT-Omni. We can recreate the answer to be something like "Hello, iam Jade from Homebrew ..."
Link Data: https://huggingface.co/datasets/gpt-omni/VoiceAssistant-400K.
Along with this, the assistant also need function calling ability so i suggest these function calling data: 
- https://huggingface.co/datasets/glaiveai/glaive-function-calling-v2
- https://huggingface.co/datasets/NousResearch/hermes-function-calling-v1
- https://huggingface.co/glaiveai/glaive-function-calling-v1
- https://huggingface.co/datasets/Salesforce/xlam-function-calling-60k

**Comment by dan-homebrew** [comment]
@bachvudinh I've renamed the Issue to be more specific to datasets

**Comment by tikikun** [comment]
it seems this is done or stale?
