### ISSUE TITLE
chore: Sync training code from upstream

### ISSUE THREAD

**Issue by bachvudinh** [homebrewltd/ichigo#77]
### Description:
This chore involves syncing the training code with the latest updates from the upstream repository to ensure our codebase remains up-to-date.

### Tasks:
-  Pull the latest changes from the upstream repository.
-  Resolve any merge conflicts.
-  Test the synchronized code to ensure all functionality remains intact.
-  Update dependent files or configurations if necessary.

### Expected Outcome:
The training code will be synchronized with the upstream repository, ensuring we are aligned with the latest features, improvements, and bug fixes.

**Comment by bachvudinh** [comment]
Here is the report format when we finish uupdating the code:

Sync completed ✅

I've successfully synced our training code with the upstream repository. Here's a summary of the changes:

- New features incorporated:
  - [Brief description of new feature 1]
  - [Brief description of new feature 2]
- Bug fixes included:
  - [Brief description of bug fix 1]
  - [Brief description of bug fix 2]

The training test runs successfully and  the code is ready for review.

@[members] Please take a look when you have a moment.

**Comment by bachvudinh** [comment]
Create A PR here: https://github.com/homebrewltd/torchtune/pull/2. cc @tikikun

**Comment by tikikun** [comment]
it's done
