### ISSUE TITLE
idea: official docker image / container builds

### ISSUE THREAD

**Issue by sammcj** [homebrewltd/ichigo#95]
### Problem Statement

Making it easier to deploy ichigo as immutable infra

### Idea

It would be great if there was an official docket image (or Dockerfile) and docker-compose example.

**Comment by bachvudinh** [comment]
Thanks for reaching out! We're actually moving it to a different repository—feel free to check it out: https://github.com/homebrewltd/ichigo-demo/tree/docker/docker/llama3s.
