### ISSUE TITLE
Reproducing the OpenHermes and Alpaca Audio Evals

### ISSUE THREAD

**Issue by Helw150** [homebrewltd/ichigo#98]
Hi Ichigo Team! Great work!

I'm hoping to reproduce the experimental setup you report for Alpaca and OpenHermes audio! I couldn't find code to reproduce that setup here, especially the prompt used for the LLM as a judge.

In June, we released an open-source Speech LLM called DiVA: https://huggingface.co/WillHeld/DiVA-llama-3-v0-8b

I'd love to see how it compares to Ichigo on these evals, but want to make sure I have the same setup as you all!

**Comment by bachvudinh** [comment]
hi @Helw150, to reproduce the result on speech instruction bench please go to our fork of Audio Bench repo here: https://github.com/homebrewltd/AudioBench. please follow the instruction on the readme file to add new model.

**Comment by Helw150** [comment]
Ah - I had missed the fork! Thanks!
